namespace CuteVideoEditor_Video
{
    enum LogLevel
    {
        Panic = 0,
        Fatal = 8,
        Error = 16,
        Warning = 24,
        Info = 32,
        Verbose = 40,
        Debug = 48,
        Trace = 56
    };

    interface IFFmpegLogProvider
    {
        void Log(LogLevel level, String message);
    }

    static runtimeclass FFmpegLogging 
    {
        static LogLevel LogLevel;
        static IFFmpegLogProvider LogProvider;
    }
}
